"""rename department

Revision ID: 64164982f6a8
Revises: 682ba58c9f9b
Create Date: 2024-06-04 13:30:08.393284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64164982f6a8'
down_revision = '682ba58c9f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
