"""add Department

Revision ID: 682ba58c9f9b
Revises: 622fc2dc5fb0
Create Date: 2024-06-04 13:24:14.704017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682ba58c9f9b'
down_revision = '622fc2dc5fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
